version: '3.8'

services:
    to-do-list:
        build:
            dockerfile: Dockerfile
        image: to-do-list
        container_name: to_do_app
        working_dir: /var/www/to-do-list
        volumes:
            - .:/var/www/to-do-list

    webserver:
        image: nginx:alpine
        container_name: nginx_webserver
        volumes:
            - .:/var/www/to-do-list
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8081:80"
        depends_on:
            - to-do-list


